// src-react/components/navigation/wird/WirdDetail.tsx
import { useState } from 'react'

import type { BrowserNotificationState, QuranRef, SurahCount, WirdSummary, WirdUnit } from '../../../continuity/wird/types'
import { Button, Checkbox, Input } from '../../ui'

export type WirdSetupPayload = {
  targetDays: number | null
  targetEndOn: string | null
  unit: WirdUnit
  startMode: 'current' | 'beginning'
  reminderEnabled: boolean
  reminderTime: string
  browserNotifications: BrowserNotificationState
}

type WirdDetailProps = {
  counts?: SurahCount[]
  currentPosition: QuranRef | null
  onBack: () => void
  onCreate: (payload: WirdSetupPayload) => void
  onContinue: () => void
  onReset: () => void
  onRequestBrowserNotifications: () => BrowserNotificationState | Promise<BrowserNotificationState>
  summary: WirdSummary
}

const UNITS: WirdUnit[] = ['juz', 'hizb', 'page', 'verse']

export function WirdDetail({
  currentPosition,
  onBack,
  onCreate,
  onContinue,
  onReset,
  onRequestBrowserNotifications,
  summary,
}: WirdDetailProps) {
  const [targetMode, setTargetMode] = useState<'preset' | 'custom'>('preset')
  const [targetDays, setTargetDays] = useState<number | null>(null)
  const [targetEndOn, setTargetEndOn] = useState('')
  const [unit, setUnit] = useState<WirdUnit>('juz')
  const [startMode, setStartMode] = useState<'current' | 'beginning'>('current')
  const [reminderEnabled, setReminderEnabled] = useState(false)
  const [reminderTime, setReminderTime] = useState('08:00')
  const [notificationState, setNotificationState] = useState<BrowserNotificationState | null>(null)
  const [confirmingReset, setConfirmingReset] = useState(false)
  const [editing, setEditing] = useState(false)
  const activePlan = summary.plan
  const currentNotificationState = notificationState ?? activePlan?.reminder.browserNotifications ?? 'default'
  const currentRefLabel = currentPosition ? `${currentPosition.surah}:${currentPosition.verse}` : '1:1'
  const canCreate = (targetMode === 'preset' ? targetDays !== null : targetEndOn.length > 0)
    && (startMode === 'beginning' || currentPosition !== null)

  function selectPreset(days: number): void {
    setTargetMode('preset')
    setTargetDays(days)
    setTargetEndOn('')
  }

  function startEditing(): void {
    setEditing(true)
    if (!activePlan) return
    setUnit(activePlan.unit)
    setReminderEnabled(activePlan.reminder.enabled)
    setReminderTime(activePlan.reminder.time)
    setNotificationState(activePlan.reminder.browserNotifications)
    setTargetMode('custom')
    setTargetDays(null)
    setTargetEndOn(activePlan.targetEndOn)
  }

  function submitCreate(): void {
    if (!canCreate) return
    onCreate({
      browserNotifications: currentNotificationState,
      reminderEnabled,
      reminderTime,
      startMode,
      targetDays: targetMode === 'preset' ? targetDays : null,
      targetEndOn: targetMode === 'custom' ? targetEndOn : null,
      unit,
    })
  }

  async function requestNotifications(): Promise<void> {
    const state = await onRequestBrowserNotifications()
    setNotificationState(state)
  }

  const showEditor = summary.state === 'no-plan' || editing

  return (
    <section aria-labelledby="wird-detail-title" className="qar-react-wird-detail">
      <div className="qar-react-wird-detail-head">
        <Button aria-label="Back" className="qar-react-wird-back" onClick={onBack} size="sm" variant="ghost">Back</Button>
        <h2 className="qar-react-wird-detail-title" id="wird-detail-title">Daily Wird</h2>
      </div>

      {showEditor ? (
        <div className="qar-react-wird-setup">
          <div className="qar-react-wird-setup-intro">
            <p className="qar-react-wird-eyebrow">Plan setup</p>
            <p className="qar-react-wird-help">Choose a finish target and QuranAtlas will size each daily reading.</p>
          </div>

          <section className="qar-react-wird-field" aria-label="Completion target">
            <div className="qar-react-wird-field-head">
              <span className="qar-react-wird-field-label">Completion target</span>
              <span className="qar-react-wird-field-value">{targetMode === 'custom' ? 'Custom' : targetDays ? `${targetDays} days` : 'Choose'}</span>
            </div>
            <div className="qar-react-wird-options" role="group" aria-label="Completion target">
              {[7, 30, 90].map((days) => (
                <Button
                  aria-pressed={targetMode === 'preset' && targetDays === days}
                  className="qar-react-wird-option"
                  key={days}
                  onClick={() => selectPreset(days)}
                  size="sm"
                  variant={targetMode === 'preset' && targetDays === days ? 'secondary' : 'ghost'}
                >
                  {days} days
                </Button>
              ))}
              <Button
                aria-pressed={targetMode === 'custom'}
                className="qar-react-wird-option"
                onClick={() => {
                  setTargetMode('custom')
                  setTargetDays(null)
                }}
                size="sm"
                variant={targetMode === 'custom' ? 'secondary' : 'ghost'}
              >
                Custom date
              </Button>
            </div>
            {targetMode === 'custom' && (
              <Input
                className="qar-react-wird-input"
                label="Finish date"
                onChange={(event) => setTargetEndOn(event.currentTarget.value)}
                type="date"
                value={targetEndOn}
              />
            )}
          </section>

          <section className="qar-react-wird-field" aria-label="Display unit">
            <div className="qar-react-wird-field-head">
              <span className="qar-react-wird-field-label">Display unit</span>
              <span className="qar-react-wird-field-value">{unit}</span>
            </div>
            <div className="qar-react-wird-options" role="group" aria-label="Display unit">
              {UNITS.map((nextUnit) => (
                <Button
                  aria-pressed={unit === nextUnit}
                  className="qar-react-wird-option"
                  key={nextUnit}
                  onClick={() => setUnit(nextUnit)}
                  size="sm"
                  variant={unit === nextUnit ? 'secondary' : 'ghost'}
                >
                  {nextUnit}
                </Button>
              ))}
            </div>
          </section>

          <section className="qar-react-wird-field" aria-label="Start point">
            <div className="qar-react-wird-field-head">
              <span className="qar-react-wird-field-label">Start point</span>
              <span className="qar-react-wird-field-value">{startMode === 'current' ? currentRefLabel : '1:1'}</span>
            </div>
            <div className="qar-react-wird-options" role="group" aria-label="Start point">
              <Button
                aria-pressed={startMode === 'current'}
                className="qar-react-wird-option"
                disabled={!currentPosition}
                onClick={() => setStartMode('current')}
                size="sm"
                variant={startMode === 'current' ? 'secondary' : 'ghost'}
              >
                Current position {currentRefLabel}
              </Button>
              <Button
                aria-pressed={startMode === 'beginning'}
                className="qar-react-wird-option"
                onClick={() => setStartMode('beginning')}
                size="sm"
                variant={startMode === 'beginning' ? 'secondary' : 'ghost'}
              >
                Beginning 1:1
              </Button>
            </div>
          </section>

          <section className="qar-react-wird-field qar-react-wird-field--reminder" aria-label="Daily Wird reminders">
            <Checkbox
              checked={reminderEnabled}
              className="qar-react-wird-reminder"
              label="Reminder"
              onCheckedChange={(checked) => setReminderEnabled(checked === true)}
            />
            {reminderEnabled && (
              <>
                <Input
                  className="qar-react-wird-input"
                  label="Reminder time"
                  onChange={(event) => setReminderTime(event.currentTarget.value)}
                  type="time"
                  value={reminderTime}
                />
                {currentNotificationState === 'unsupported' && <p className="qar-react-wird-note">In-app reminder only</p>}
                {currentNotificationState === 'granted' && <p className="qar-react-wird-note">Browser notifications enabled</p>}
                {currentNotificationState === 'denied' && <p className="qar-react-wird-note">Blocked in browser settings</p>}
                {currentNotificationState !== 'unsupported' && currentNotificationState !== 'granted' && (
                  <Button className="qar-react-wird-secondary" onClick={() => { void requestNotifications() }} size="sm" variant="secondary">
                    {currentNotificationState === 'denied' ? 'Request again' : 'Enable browser notifications'}
                  </Button>
                )}
              </>
            )}
          </section>

          <Button className="qar-react-wird-primary" disabled={!canCreate} onClick={submitCreate}>
            {summary.state === 'no-plan' ? 'Create Plan' : 'Save Plan'}
          </Button>
        </div>
      ) : (
        <div className="qar-react-wird-current">
          <p className="qar-react-wird-range">{summary.todayRangeLabel}</p>
          <p className="qar-react-wird-remaining">{summary.remainingLabel}</p>
          {summary.reminderLabel && <p className="qar-react-wird-reminder-line">{summary.reminderLabel}</p>}
          <Button className="qar-react-wird-primary" disabled={summary.state === 'plan-complete'} onClick={onContinue}>
            {summary.state === 'plan-complete' ? 'Plan complete' : 'Continue Wird'}
          </Button>
          <Button className="qar-react-wird-secondary" onClick={startEditing} variant="secondary">Edit Plan</Button>
          <Button className="qar-react-wird-danger" onClick={() => setConfirmingReset(true)} variant="danger">Reset Plan</Button>
          {confirmingReset && (
            <Button className="qar-react-wird-danger" onClick={onReset} variant="danger">Confirm reset</Button>
          )}
        </div>
      )}
    </section>
  )
}

// src/read/wird/WirdDetail.svelte
<script lang="ts">
  import type { GlobalPosition } from '../../configure/state.svelte'
  import type { BrowserNotificationState, WirdPlan, WirdSummary, WirdUnit } from './types'

  export type SetupPayload = {
    targetDays: number | null
    targetEndOn: string | null
    unit: WirdUnit
    startMode: 'current' | 'beginning'
    reminderEnabled: boolean
    reminderTime: string
    browserNotifications: BrowserNotificationState
  }

  type Props = {
    summary: WirdSummary
    currentPosition: GlobalPosition
    onBack: () => void
    onCreate: (payload: SetupPayload) => void
    onContinue: () => void
    onReset: () => void
    onRequestBrowserNotifications: () => BrowserNotificationState | Promise<BrowserNotificationState>
  }

  const {
    summary,
    currentPosition,
    onBack,
    onCreate,
    onContinue,
    onReset,
    onRequestBrowserNotifications,
  }: Props = $props()

  let targetMode = $state<'preset' | 'custom'>('preset')
  let targetDays = $state<number | null>(null)
  let targetEndOn = $state<string>('')
  let unit = $state<WirdUnit>('juz')
  let startMode = $state<'current' | 'beginning'>('current')
  let reminderEnabled = $state(false)
  let reminderTime = $state('08:00')
  let requestedNotificationState = $state<BrowserNotificationState | null>(null)
  let confirmingReset = $state(false)
  let editing = $state(false)

  const currentRefLabel = $derived(currentPosition ? `${currentPosition.surah}:${currentPosition.verse}` : '1:1')
  const activePlan = $derived(summary.plan)
  const currentNotificationState = $derived<BrowserNotificationState>(
    requestedNotificationState ?? activePlan?.reminder.browserNotifications ?? 'default',
  )
  const canCreate = $derived(
    (targetMode === 'preset' ? targetDays !== null : targetEndOn.length > 0)
      && (startMode === 'beginning' || currentPosition !== null),
  )

  function loadFromPlan(plan: WirdPlan): void {
    unit = plan.unit
    reminderEnabled = plan.reminder.enabled
    reminderTime = plan.reminder.time
    requestedNotificationState = plan.reminder.browserNotifications
    targetMode = 'custom'
    targetDays = null
    targetEndOn = plan.targetEndOn
  }

  function startEditing(): void {
    editing = true
    if (activePlan) { loadFromPlan(activePlan) }
  }

  function submitCreate(): void {
    if (!canCreate) { return }
    onCreate({
      targetDays: targetMode === 'preset' ? targetDays : null,
      targetEndOn: targetMode === 'custom' ? targetEndOn : null,
      unit,
      startMode,
      reminderEnabled,
      reminderTime,
      browserNotifications: currentNotificationState,
    })
  }

  async function requestNotifications(): Promise<void> {
    const state = await onRequestBrowserNotifications()
    requestedNotificationState = state
  }
</script>

<section class="qa-wird-detail" aria-labelledby="wird-detail-title">
  <div class="qa-wird-detail-head">
    <button type="button" class="qa-wird-back" aria-label="Back" onclick={onBack}>Back</button>
    <h2 id="wird-detail-title" data-testid="wird-detail-title">Daily Wird</h2>
  </div>

  {#if summary.state === 'no-plan' || editing}
    <div class="qa-wird-setup">
      <div class="qa-wird-setup-intro">
        <p class="qa-wird-eyebrow">Plan setup</p>
        <p class="qa-wird-help">Choose a finish target and QuranAtlas will size each daily reading.</p>
      </div>

      <div class="qa-wird-field">
        <div class="qa-wird-field-head">
          <span class="qa-wird-field-label">Completion target</span>
          <span class="qa-wird-field-value">{targetMode === 'custom' ? 'Custom' : targetDays ? `${targetDays} days` : 'Choose'}</span>
        </div>
        <div class="qa-wird-targets" role="group" aria-label="Completion target">
          <button type="button" data-testid="wird-target-7" aria-pressed={targetMode === 'preset' && targetDays === 7} class="qa-wird-option" class:qa-wird-option--on={targetMode === 'preset' && targetDays === 7} onclick={() => { targetMode = 'preset'; targetDays = 7 }}>7 days</button>
          <button type="button" data-testid="wird-target-30" aria-pressed={targetMode === 'preset' && targetDays === 30} class="qa-wird-option" class:qa-wird-option--on={targetMode === 'preset' && targetDays === 30} onclick={() => { targetMode = 'preset'; targetDays = 30 }}>30 days</button>
          <button type="button" data-testid="wird-target-90" aria-pressed={targetMode === 'preset' && targetDays === 90} class="qa-wird-option" class:qa-wird-option--on={targetMode === 'preset' && targetDays === 90} onclick={() => { targetMode = 'preset'; targetDays = 90 }}>90 days</button>
          <button type="button" data-testid="wird-target-custom" aria-pressed={targetMode === 'custom'} class="qa-wird-option" class:qa-wird-option--on={targetMode === 'custom'} onclick={() => { targetMode = 'custom'; targetDays = null }}>Custom date</button>
        </div>

        {#if targetMode === 'custom'}
          <input
            type="date"
            class="qa-wird-input"
            data-testid="wird-finish-date"
            aria-label="Finish date"
            bind:value={targetEndOn}
          />
        {/if}
      </div>

      <div class="qa-wird-field">
        <div class="qa-wird-field-head">
          <span class="qa-wird-field-label">Display unit</span>
          <span class="qa-wird-field-value">{unit}</span>
        </div>
        <div class="qa-wird-units" role="group" aria-label="Display unit">
          {#each ['juz', 'hizb', 'page', 'verse'] as key (key)}
            <button type="button" aria-pressed={unit === key} class="qa-wird-option" class:qa-wird-option--on={unit === key} onclick={() => { unit = key as WirdUnit }}>{key}</button>
          {/each}
        </div>
      </div>

      <div class="qa-wird-field">
        <div class="qa-wird-field-head">
          <span class="qa-wird-field-label">Start point</span>
          <span class="qa-wird-field-value">{startMode === 'current' ? currentRefLabel : '1:1'}</span>
        </div>
        <div class="qa-wird-start" role="group" aria-label="Start point">
          <button type="button" aria-pressed={startMode === 'current'} class="qa-wird-option" class:qa-wird-option--on={startMode === 'current'} onclick={() => { startMode = 'current' }}>Current position <span class="qa-wird-option-ref">{currentRefLabel}</span></button>
          <button type="button" aria-pressed={startMode === 'beginning'} class="qa-wird-option" class:qa-wird-option--on={startMode === 'beginning'} onclick={() => { startMode = 'beginning' }}>Beginning <span class="qa-wird-option-ref">1:1</span></button>
        </div>
      </div>

      <div class="qa-wird-field qa-wird-field--reminder">
        <label class="qa-wird-reminder">
          <input type="checkbox" bind:checked={reminderEnabled} />
          Reminder
        </label>

        {#if reminderEnabled}
          <input type="time" class="qa-wird-input" bind:value={reminderTime} aria-label="Reminder time" />
          {#if currentNotificationState === 'unsupported'}
            <p class="qa-wird-note">In-app reminder only</p>
          {:else if currentNotificationState === 'granted'}
            <p class="qa-wird-note">Browser notifications enabled</p>
          {:else if currentNotificationState === 'denied'}
            <p class="qa-wird-note">Blocked in browser settings</p>
            <button
              type="button"
              class="qa-wird-secondary"
              data-testid="wird-enable-browser-notifications"
              onclick={() => { void requestNotifications() }}
            >
              Request again
            </button>
          {:else}
            <button
              type="button"
              class="qa-wird-secondary"
              data-testid="wird-enable-browser-notifications"
              onclick={() => { void requestNotifications() }}
            >
              Enable browser notifications
            </button>
          {/if}
        {/if}
      </div>

      <button type="button" class="qa-wird-primary" data-testid="wird-create" disabled={!canCreate} onclick={submitCreate}>
        {summary.state === 'no-plan' ? 'Create Plan' : 'Save Plan'}
      </button>
    </div>
  {:else}
    <div class="qa-wird-current">
      <p class="qa-wird-range">{summary.todayRangeLabel}</p>
      <p class="qa-wird-remaining">{summary.remainingLabel}</p>
      {#if summary.reminderLabel}
        <p class="qa-wird-reminder-line">{summary.reminderLabel}</p>
      {/if}
      <button type="button" class="qa-wird-primary" data-testid="wird-continue" disabled={summary.state === 'plan-complete'} onclick={onContinue}>
        {summary.state === 'plan-complete' ? 'Plan complete' : 'Continue Wird'}
      </button>
      <button type="button" class="qa-wird-secondary" data-testid="wird-edit" onclick={startEditing}>Edit Plan</button>
      <button type="button" class="qa-wird-danger" data-testid="wird-reset" onclick={() => { confirmingReset = true }}>Reset Plan</button>
      {#if confirmingReset}
        <button type="button" class="qa-wird-danger" data-testid="wird-reset-confirm" onclick={onReset}>Confirm reset</button>
      {/if}
    </div>
  {/if}
</section>
