// src/components/settings/ThemeNightControls.tsx
import { CircleSlash, MoonStar, Sun } from 'lucide-react'
import type { ComponentType } from 'react'

import { Button } from '../ui'
import type { ReactNightModePreference, ReactThemePreference } from '../../storage/settings-writer'

type AppearanceIconProps = {
  size?: number
  strokeWidth?: number
  'aria-hidden'?: boolean
}

type AppearanceOption<T extends string> = {
  id: T
  icon?: ComponentType<AppearanceIconProps>
  iconId: string
  label: string
  swatch?: 'sepia'
}

const THEMES: Array<AppearanceOption<ReactThemePreference>> = [
  { id: 'light', icon: Sun, iconId: 'theme-light', label: 'Light' },
  { id: 'sepia', iconId: 'theme-sepia', label: 'Sepia', swatch: 'sepia' },
  { id: 'dark', icon: MoonStar, iconId: 'theme-dark', label: 'Dark' },
  { id: 'auto', icon: CircleSlash, iconId: 'theme-auto', label: 'Auto' },
]

const NIGHT_MODES = [
  { id: 'off', icon: NightOffIcon, iconId: 'night-off', label: 'Off' },
  { id: 'on', icon: NightOnIcon, iconId: 'night-on', label: 'On' },
  { id: 'auto', icon: NightAutoIcon, iconId: 'night-auto', label: 'Auto' },
] satisfies Array<AppearanceOption<ReactNightModePreference>>

export function ThemeNightControls({
  nightMode,
  onNightModeChange,
  onThemeChange,
  theme,
}: {
  nightMode: ReactNightModePreference
  onNightModeChange: (value: ReactNightModePreference) => void
  onThemeChange: (value: ReactThemePreference) => void
  theme: ReactThemePreference
}) {
  return (
    <div className="qar-react-settings-theme-night" aria-label="Theme and night mode">
      <section className="qar-react-settings-appearance-panel" aria-labelledby="qar-react-settings-theme">
        <h4 className="qar-react-settings-appearance-title" id="qar-react-settings-theme">Theme</h4>
        <div className="qar-react-settings-theme-strip" role="group" aria-label="Theme">
          {THEMES.map((option) => (
            <AppearanceChoice
              active={theme === option.id}
              icon={option.icon}
              iconId={option.iconId}
              key={option.id}
              label={option.label}
              onClick={() => onThemeChange(option.id)}
              prefix="Theme"
              swatch={option.swatch}
            />
          ))}
        </div>
      </section>
      <section className="qar-react-settings-appearance-panel" aria-labelledby="qar-react-settings-night">
        <h4 className="qar-react-settings-appearance-title" id="qar-react-settings-night">Night mode</h4>
        <div className="qar-react-settings-night-strip" role="group" aria-label="Night mode">
          {NIGHT_MODES.map((option) => {
            const Icon = option.icon
            return (
              <AppearanceChoice
                active={nightMode === option.id}
                icon={Icon}
                iconId={option.iconId}
                key={option.id}
                label={option.label}
                onClick={() => onNightModeChange(option.id)}
                prefix="Night mode"
              />
            )
          })}
        </div>
      </section>
    </div>
  )
}

function AppearanceChoice({
  active,
  icon: Icon,
  iconId,
  label,
  onClick,
  prefix,
  swatch,
}: {
  active: boolean
  icon?: ComponentType<AppearanceIconProps>
  iconId: string
  label: string
  onClick: () => void
  prefix: string
  swatch?: string
}) {
  return (
    <Button
      aria-label={`${prefix}: ${label}`}
      aria-pressed={active}
      className="qar-react-settings-appearance-choice"
      onClick={onClick}
      size="sm"
      variant="ghost"
    >
      <span
        className="qar-react-settings-appearance-icon"
        data-appearance-icon={iconId}
        data-swatch={swatch}
        data-testid={swatch ? 'settings-theme-swatch' : undefined}
      >
        {Icon ? <Icon aria-hidden={true} size={19} strokeWidth={1.55} /> : null}
        {swatch ? <span className="qar-react-settings-theme-swatch" data-swatch={swatch} /> : null}
      </span>
      <span className="qar-react-settings-choice-label">{label}</span>
    </Button>
  )
}

function NightOffIcon({ size = 19, strokeWidth = 1.55, 'aria-hidden': ariaHidden = true }: AppearanceIconProps) {
  return (
    <svg
      aria-hidden={ariaHidden}
      data-night-icon="sun"
      fill="none"
      height={size}
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
      viewBox="0 0 24 24"
      width={size}
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle cx="12" cy="12" r="3.55" />
      <path d="M12 2.9v2.05M12 19.05v2.05M4.24 4.24 5.7 5.7M18.3 18.3l1.46 1.46M2.9 12h2.05M19.05 12h2.05M4.24 19.76 5.7 18.3M18.3 5.7l1.46-1.46" />
    </svg>
  )
}

function NightOnIcon({ size = 19, 'aria-hidden': ariaHidden = true }: AppearanceIconProps) {
  return (
    <svg
      aria-hidden={ariaHidden}
      data-night-icon="crescent"
      fill="currentColor"
      height={size}
      viewBox="0 0 24 24"
      width={size}
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M15.38 3.88a8.2 8.2 0 1 0 4.74 13.35A8.92 8.92 0 0 1 9.8 6.86a8.82 8.82 0 0 1 5.58-2.98Z" />
    </svg>
  )
}

function NightAutoIcon({ size = 19, 'aria-hidden': ariaHidden = true }: AppearanceIconProps) {
  return (
    <svg
      aria-hidden={ariaHidden}
      data-night-icon="crescent-sparkles"
      fill="currentColor"
      height={size}
      viewBox="0 0 24 24"
      width={size}
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M10.68 10.15a5.22 5.22 0 0 0 4.4 8.1 5.64 5.64 0 1 1-4.4-8.1Z" />
      <path d="M17.18 3.75 18 5.95l2.22.82L18 7.58l-.82 2.2-.82-2.2-2.22-.81 2.22-.82.82-2.2Z" />
      <path d="M6.58 5.82 7.1 7.2l1.38.52-1.38.5-.52 1.4-.5-1.4-1.4-.5 1.4-.52.5-1.38Z" />
    </svg>
  )
}

// src/configure/settings/ThemeNightControls.svelte
<script lang="ts">
  import { settings, type NightMode } from '../state.svelte'
  import { setTheme } from '../theme'
  import { setNightMode } from '../night-mode'

  const themes = [
    { id: 'light', label: 'Light' },
    { id: 'sepia', label: 'Sepia' },
    { id: 'dark', label: 'Dark' },
    { id: 'auto', label: 'Auto' },
  ] as const
  const nightModes: Array<{ id: NightMode; label: string; icon: string }> = [
    { id: 'off', label: 'Off', icon: '☼' },
    { id: 'on', label: 'On', icon: '☾✦' },
    { id: 'auto', label: 'Auto', icon: 'A↺' },
  ]

</script>

<div class="qa-settings-theme-night" aria-label="Theme and night mode">
  <div class="qa-settings-theme-panel">
    <h3 class="qa-settings-theme-night-title qa-settings-row-label">Theme</h3>
    <div class="qa-settings-theme-grid" role="group" aria-label="Theme">
      {#each themes as theme (theme.id)}
        <button
          type="button"
          class="qa-settings-theme-option"
          class:qa-settings-theme-option--active={settings.theme === theme.id}
          aria-pressed={settings.theme === theme.id}
          onclick={() => { void setTheme(theme.id) }}
        >
          <span class="qa-settings-theme-card">
            <span
              class="qa-settings-theme-swatch"
              class:qa-settings-theme-swatch--light={theme.id === 'light'}
              class:qa-settings-theme-swatch--sepia={theme.id === 'sepia'}
              class:qa-settings-theme-swatch--dark={theme.id === 'dark'}
              class:qa-settings-theme-swatch--auto={theme.id === 'auto'}
              aria-hidden="true"
            >
              {#if theme.id === 'auto'}
                <span class="qa-settings-theme-auto-sun">☼</span>
                <span class="qa-settings-theme-auto-moon">☾</span>
              {/if}
            </span>
            {#if settings.theme === theme.id}
              <span class="qa-settings-theme-check" aria-hidden="true">✓</span>
            {/if}
            <span class="qa-settings-theme-option-label">{theme.label}</span>
          </span>
        </button>
      {/each}
    </div>
  </div>

  <div class="qa-settings-night-panel">
    <h3 class="qa-settings-theme-night-title qa-settings-row-label">Night Mode</h3>
    <div class="qa-settings-night-group" role="group" aria-label="Night mode">
      {#each nightModes as mode (mode.id)}
        <button
          type="button"
          class="qa-settings-night-choice"
          class:qa-settings-night-choice--active={settings.nightMode === mode.id}
          aria-pressed={settings.nightMode === mode.id}
          onclick={() => { void setNightMode(mode.id) }}
        >
          <span class="qa-settings-night-choice-icon" aria-hidden="true">{mode.icon}</span>
          <span class="qa-settings-night-choice-label">{mode.label}</span>
        </button>
      {/each}
    </div>
  </div>
</div>
